# ================================
#   Netlify Clean Minimal Config
#   No CSP, No Extra Headers
# ================================

[build]
  publish = "frontend"
  command = ""

# SPA Redirect (important)
# Any unknown route â†’ index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
